quarkus.http.port=8080

# Dev Services
quarkus.devservices.enabled=false

# DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecomm_db

quarkus.hibernate-orm.schema-management.strategy=none

quarkus.log.console.level=DEBUG

# Kafka
kafka.bootstrap.servers=http://localhost:19092
kafka.schema-registry.url=http://localhost:8081

# Kafka Producer
kafka.producer.order-notification.topic=product-order-topic

# Kafka Consumer
kafka.consumer.order-notification.group-id=product-order-topic-cg-01
kafka.consumer.order-notification.client-id=product-order-topic-client