quarkus.http.port=8080

# Dev Services
quarkus.devservices.enabled=false

quarkus.rest-client.logging.scope=request-response

quarkus.rest-client.financial-api.url=https://free.e-api.net.pe
quarkus.rest-client.financial-api.connect-timeout=5000
quarkus.rest-client.financial-api.read-timeout=5000