quarkus.http.port=8080

# Dev Services
quarkus.devservices.enabled=false

# DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DATABASE_USER}
quarkus.datasource.password=${DATABASE_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DATABASE_HOST}:{DATABASE_PORT}/ecomm_db

quarkus.hibernate-orm.schema-management.strategy=none

quarkus.log.console.level=ERROR

# Kafka
kafka.bootstrap.servers=${KAFKA_SERVERS}
kafka.schema-registry.url=${KAFKA_SCHEMA_REGISTRY_URL}

# Kafka Producer
kafka.producer.order-notification.topic=product-order-topic

# Kafka Consumer
kafka.consumer.order-notification.group-id=product-order-topic-cg-01
kafka.consumer.order-notification.client-id=product-order-topic-client